# Generated by Django 2.2 on 2019-05-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('card_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Card Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('erp', models.CharField(max_length=200, verbose_name='Enrollment Number')),
                ('registered', models.BooleanField(default=0, verbose_name='Registered ?')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['card_no'],
            },
        ),
        migrations.CreateModel(
            name='StudentExcelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='', verbose_name='Excel Sheet')),
            ],
            options={
                'verbose_name': 'Excel Sheet',
                'verbose_name_plural': 'Excel Sheets',
            },
        ),
    ]
