# Generated by Django 2.2 on 2019-05-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsideLaundry',
            fields=[
                ('check_in_date', models.DateTimeField(auto_now_add=True, verbose_name='Check In Date')),
                ('card_no', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='student.Student', verbose_name='Card Number')),
                ('clothes', models.IntegerField(default=15, verbose_name='Number of Clothes')),
            ],
            options={
                'verbose_name': 'Check In',
                'verbose_name_plural': 'Check In',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='ReadyBags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(verbose_name='Bag Ready ?')),
                ('card_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='circulation.InsideLaundry', verbose_name='Card Number')),
            ],
            options={
                'verbose_name': 'Ready Bag',
                'verbose_name_plural': 'Ready Bags',
            },
        ),
        migrations.CreateModel(
            name='LaundryCirculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_date', models.DateTimeField(auto_now_add=True, verbose_name='Check Out Date')),
                ('clothes', models.IntegerField(default=15, verbose_name='Number of Clothes')),
                ('check_in_date', models.DateTimeField(null=True, verbose_name='Check In Date')),
                ('card_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Student', verbose_name='Card Number')),
            ],
            options={
                'verbose_name': 'Laundry Circulation',
                'verbose_name_plural': 'Laundry Circulation',
            },
        ),
    ]
