# Generated by Django 2.2 on 2019-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insidelaundry',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Bag Ready ?'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReadyBags',
        ),
    ]
